# Site settings
title: The Mist
email: isolatedislet@gmail.com
url: https://example.github.io
description: The more you know who you are and what you want,the less you let things upset you.

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/TimingSea
  - title: facebook
    url:
  - title: stack-overflow
    url: 
  - title: bitbucket
    url: 
  - title: github
    url: https://github.com/BaiZhaohui

# Build settings
markdown: kramdown
permalink: pretty
